version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0.32
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local